### ISSUE TITLE
 image = "36148574" does not exist...

### ISSUE THREAD

**Issue by jimangel** [nkhare/k8s-cicd-webinars#2]
Trying to recreate this k8s DO terraform ./script deploy, cannot find image based on this tag.

I can search all image ids with: curl -X GET --silent "https://api.digitalocean.com/v2/images?per_page=999" -H "Authorization: Bearer $TOKEN" | jq '.'

**Comment by nkhare** [comment]
@jimangel that script used one of our image snapshot.  Somehow we missed it to make it generic. It is fixed now.
