### ISSUE TITLE
while using buildah for project atomic

### ISSUE THREAD

**Issue by manishhub9** [nkhare/k8s-cicd-webinars#6]
I am using digitalocean ubuntu vm for that. and i am facing this issue:

```
buildah build-using-dockerfile -t nkhare/rsvpapp:buildah github.com/cloudyuga/rsvpapp
STEP 1: FROM teamcloudyuga/python:alpine
STEP 2: COPY . /usr/src/app
STEP 3: WORKDIR /usr/src/app
STEP 4: ENV LINK http://www.meetup.com/cloudyuga/
STEP 5: ENV TEXT1 CloudYuga
STEP 6: ENV TEXT2 Garage RSVP!
STEP 7: ENV LOGO https://raw.githubusercontent.com/cloudyuga/rsvpapp/master/static/cloudyuga.png
STEP 8: ENV COMPANY CloudYuga Technology Pvt. Ltd.
STEP 9: RUN pip3 install -r requirements.txt
error running container: error creating container for [/bin/sh -c pip3 install -r requirements.txt]: : exec: "runc": executable file not found in $PATH
error building at step {Env:[COMPANY=CloudYuga Technology Pvt. Ltd. LOGO=https://raw.githubusercontent.com/cloudyuga/rsvpapp/master/static/cloudyuga.png TEXT2=Garage RSVP! TEXT1=CloudYuga LINK=http://www.meetup.com/cloudyuga/ PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin LANG=C.UTF-8 GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D PYTHON_VERSION=3.6.0b1 PYTHON_PIP_VERSION=8.1.2      LINK=http://www.meetup.com/cloudyuga/ TEXT1=CloudYuga TEXT2=Garage RSVP! LOGO=https://raw.githubusercontent.com/cloudyuga/rsvpapp/master/static/cloudyuga.png COMPANY=CloudYuga Technology Pvt. Ltd.] Command:run Args:[pip3 install -r requirements.txt] Flags:[] Attrs:map[] Message:RUN pip3 install -r requirements.txt Original:RUN pip3 install -r requirements.txt}: exit status 1
```
i am using this command on root and i follow all the step given in the k8s-cicd-webinars/webinar1/1-container-images/3-projectatomic-buildah. Please help me and thanks for your time.

**Comment by giri021** [comment]
cp ~/buildah/src/github.com/opencontainers/runc/runc /usr/bin/. 
 >>> i get error for this step:
cp: cannot stat '/home/giri021/buildah/src/github.com/opencontainers/runc/runc': No such file or directory
How to fix this?

**Comment by mstavares** [comment]
Hi,

I have the same issue that is described here.

error:
error running container: error creating container for [/bin/sh -c mkdir -p /usr/src/app]: : exec: "runc": executable file not found in $PATH

This is running in a docker:
RUN sudo apt-get install golang-go -y

RUN mkdir ~/buildah
RUN cd ~/buildah
RUN export GOPATH=`pwd`
RUN git clone https://github.com/projectatomic/buildah ./src/github.com/projectatomic/buildah
RUN sudo cp -a /projects/src/github.com/projectatomic/buildah/vendor/github.com/opencontainers/runc /usr/bin/.
RUN sudo apt-get install buildah -y

Am I missing something?

Thanks,
